unit_test/data.h: include missing <stdint.h> for uint16_t (gcc-13 fix)
Without the change build fails on gcc-13 as:

    /build/source/unit_test/data.h:37:9: error: 'uint16_t' does not name a type
       37 |         uint16_t i;
          |         ^~~~~~~~
    /build/source/unit_test/data.h:33:1: note: 'uint16_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
       32 | #include <string.h>
      +++ |+#include <cstdint>